@startuml

interface RecordDAO {
    +{abstract} doAdd(Record record):void
    +{abstract} getRecords():List<Record>
}

class RecordDAOImpl {
    +doAdd(Record record):void
    +getRecords():List<Record>
}

class Record {
    -String name
    -int score
    -Date date

    +
}






@enduml